from .embedding_maml_few_shot_classifier import EmbeddingMAMLFewShotClassifier
from .fine_tune_from_pretrained_few_shot_classifier import FineTuneFromPretrainedFewShotClassifier
from .fine_tune_from_scratch_few_shot_classifier import FineTuneFromScratchFewShotClassifier
from .maml_few_shot_classifier import MAMLFewShotClassifier
from .matching_network_few_shot_classifier import MatchingNetworkFewShotClassifier
from .vgg_maml_few_shot_classifier import VGGMAMLFewShotClassifier
